spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vendorApp?useSSL=false
    username: root
    password: dummy123

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#JPA Settings:
  jpa.hibernate.ddl_auto: update

server:
  port: 8090